import {token, token_type, word} from 'allang-compiler-base'

function _token(keyword: string): word {
    return new word(keyword)
}

export default [
    //语法块
    _token('if')
    , _token('else if')
    , _token('else')
    , _token('for')
    , _token('while')
    , _token('do')
    , _token('switch')
    , _token('case')
    , _token('default')
    , _token('try')
    , _token('catch')
    , _token('finally')
    //语句
    , _token('break')
    , _token('continue')
    , _token('return')
    , _token('var')
    , _token('new')
    , _token('delete')
    , _token('typeof')
    , _token('void')
    , _token('instanceof')
    //封装块
    , _token('class')
    , _token('interface')
    , _token('enum')
    //标识符
    , _token('module')
    , _token('import')
    , _token('as')
    //变量
    , _token('this')
    , _token('super')
    //数学运算符
    , _token('+')
    , _token('-')
    , _token('*')
    , _token('/')
    , _token('%')
    , _token('<<')
    , _token('>>')
    , _token('&')
    , _token('|')
    , _token('^')
    , _token('~')
    //逻辑运算符
    , _token('!')
    , _token('&&')
    , _token('||')
    //赋值运算符
    , _token('=')
    , _token('+=')
    , _token('-=')
    , _token('*=')
    , _token('/=')
    , _token('%=')
    , _token('<<=')
    , _token('>>=')
    , _token('&=')
    , _token('|=')
    , _token('^=')
    , _token('~=')
    , _token('++')
    , _token('--')
    //比较运算符
    , _token('<')
    , _token('>')
    , _token('<=')
    , _token('>=')
    , _token('==')
    , _token('!=')
    //括号和其他标点符号
    , _token('(')
    , _token(')')
    , _token('{')
    , _token('}')
    , _token('[')
    , _token(']')
    , _token(';')
    , _token(',')
    , _token('.')
    , _token(':')
    , _token('?')
    , _token('@')
    //类型
    , _token('void')
    , _token('boolean')
    , _token('number')
    , _token('string')
    , _token('map')
    //值
    , _token('true')
    , _token('false')
    , _token('null')
    //修饰符
    , _token('async')
    , _token('sync')
    , _token('await')
    , _token('static')
    , _token('public')
    , _token('private')
    , _token('final')
    , _token('implements')
    //其他
    , _token('=>')
    , _token('...')
    //虚拟机直接操作
    ,_token('vm')
]