import {token, token_type, word} from 'allang-compiler-base'

function _token(keyword: string): word {
    return new word(keyword)
}

export default [
    // 块定义关键字
    _token('function')
    , _token('class')
    , _token('interface')
    , _token('enum')
    , _token('module')
    , _token('var')
    , _token('const')
    , _token('of')
    , _token('implements')
    // 控制流
    , _token('if')
    , _token('else')
    , _token('switch')
    , _token('case')
    , _token('default')
    , _token('for')
    , _token('foreach')
    , _token('while')
    , _token('do')
    , _token('try')
    , _token('catch')
    , _token('finally')
    // 语句
    , _token('break')
    , _token('continue')
    , _token('return')
    , _token('new')
    , _token('delete')
    , _token('typeof')
    , _token('throw')
    , _token('vm')
    , _token('await')
    , _token('import')
    , _token('as')
    // 修饰符
    , _token('async')
    , _token('sync')
    , _token('static')
    , _token('unstatic')
    , _token('public')
    , _token('private')
    , _token('final')
    // 类型
    , _token('void')
    , _token('boolean')
    , _token('number')
    , _token('string')
    , _token('map')
    , _token('array')
    , _token('any')
    // 值
    , _token('true')
    , _token('false')
    , _token('null')
    // 逻辑运算符
    , _token('!')
    , _token('&&')
    , _token('||')
    // 赋值运算符 (复合运算符必须在单字符运算符之前)
    , _token('+=')
    , _token('-=')
    , _token('*=')
    , _token('/=')
    , _token('%=')
    , _token('<<=')
    , _token('>>=')
    , _token('&=')
    , _token('|=')
    , _token('^=')
    , _token('++')
    , _token('--')
    // 比较运算符
    , _token('<')
    , _token('>')
    , _token('<=')
    , _token('>=')
    , _token('==')
    , _token('!=')
    // 数学运算符 (单字符 — 必须在复合运算符之后定义)
    , _token('+')
    , _token('-')
    , _token('*')
    , _token('/')
    , _token('%')
    , _token('<<')
    , _token('>>')
    , _token('&')
    , _token('|')
    , _token('^')
    , _token('~')
    // 括号和其他标点符号
    , _token('(')
    , _token(')')
    , _token('{')
    , _token('}')
    , _token('[')
    , _token(']')
    , _token(';')
    , _token(',')
    , _token('.')
    , _token(':')
    , _token('?')
    , _token('@')
    , _token('=>')
    , _token('->')
    , _token('...')
    , _token('[]')
]